### ISSUE TITLE
Update artifact download and upload to use the toolkit @actions/artifact 2.0 or later API to be compatible with actions/upload-artifact@v4

### ISSUE THREAD

**Issue by roxanneskelly** [secondlife/action-autobuild-release#46]
The artifact download and upload code uses an older API to access artifacts, which is not compatible with actions/upload-artifact@v4.  It's desirable to move toward that API, and secondlife/actions-autobuild should use that API to upload it's autobuild artifacts.

**Comment by bennettgoble** [comment]
Fixed in https://github.com/secondlife/action-autobuild-release/pull/47
